//
//  MenuRepository.swift
//  refNot
//
//  Created by Gleb Shendrik on 08/10/2018.
//  Copyright © 2018 geeksdevelopers. All rights reserved.
//

struct MenuRepository {
    static let menus = [Menu(id: 21212,
                               title: "Star Trek Beyond",
                               description: MenusHelper.startrekBeyondDescription,
                               year: 2016,
                               budget: 185000000,
                               director: "Justin Lin",
                               writer: "S. Pegg",
                               image: "startrek",
                               watched: false),
                         Menu(id: 14323,
                               title: "Starwars: The force awakens",
                               description: MenusHelper.starwarsDescription,
                               year: 2015,
                               budget: 245000000,
                               director: "JJ. Abrams",
                               writer: "L. Kasdan",
                               image: "starwars",
                               watched: false),
                         Menu(id: 23452,
                               title: "Avatar",
                               description: MenusHelper.avatarDescription,
                               year: 2009,
                               budget: 237000000,
                               director: "J. Cameron",
                               writer: "J. Cameron",
                               image: "avatar",
                               watched: false),
                         Menu(id: 35423,
                               title: "Blade Runner",
                               description: MenusHelper.bladeRunnerDescription,
                               year: 1982,
                               budget: 28000000,
                               director: "R. Scott",
                               writer: "H. Fetcher",
                               image: "bladerunner",
                               watched: false),
                         Menu(id: 43424,
                               title: "The Terminator",
                               description: MenusHelper.terminatorDescription,
                               year: 1984,
                               budget: 6400000,
                               director: "J. Cameron",
                               writer: "J. Cameron",
                               image: "terminator",
                               watched: true),
                         Menu(id: 55423,
                               title: "Predator",
                               description: MenusHelper.predatorDescription,
                               year: 1987,
                               budget: 15000000,
                               director: "J. McTiernan",
                               writer: "J. Thomas",
                               image: "predator",
                               watched: true),
                         Menu(id: 64323,
                               title: "Dune",
                               description: MenusHelper.duneDescription,
                               year: 1984,
                               budget: 40000000,
                               director: "D. Lynch",
                               writer: "F. Herbert",
                               image: "dune",
                               watched: true),
                         Menu(id: 7253,
                               title: "First Constact",
                               description: MenusHelper.firstContactDescription,
                               year: 1996,
                               budget: 45000000,
                               director: "J. Frakes",
                               writer: "G. Roddenberry",
                               image: "firstcontact",
                               watched: true),
                         Menu(id: 5864,
                               title: "Dune",
                               description: MenusHelper.duneDescription,
                               year: 1984,
                               budget: 40000000,
                               director: "D. Lynch",
                               writer: "F. Herbert",
                               image: "dune",
                               watched: true),
                         Menu(id: 9432,
                               title: "First Constact",
                               description: MenusHelper.firstContactDescription,
                               year: 1996,
                               budget: 45000000,
                               director: "J. Frakes",
                               writer: "G. Roddenberry",
                               image: "firstcontact",
                               watched: true)]
}
